export const SIZE_CELL = 40
export const INDENT_BETWEEN_CELLS = 2
export const INDENT_BETWEEN_SECTION_CELLS = 4
export const COUNT_CELLS_INSIDE_SECTION = 3
export const COUNT_SECTIONS = 3
export const AREA_INDENT_INSIDE_CELL = 2
export const AREA_INDENT_INSIDE_CELL_TOPSIDE = AREA_INDENT_INSIDE_CELL
export const AREA_INDENT_INSIDE_CELL_BOTTOMSIDE = SIZE_CELL - AREA_INDENT_INSIDE_CELL
